
import React from 'react';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const AboutQuantum: React.FC = () => {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>About Quantum Randomness</CardTitle>
        <CardDescription>
          Understanding true randomness through quantum mechanics
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible className="w-full">
          <AccordionItem value="what-is-qrng">
            <AccordionTrigger>What is a Quantum Random Number Generator?</AccordionTrigger>
            <AccordionContent>
              <p className="text-sm text-muted-foreground mb-2">
                A Quantum Random Number Generator (QRNG) creates true random numbers by measuring quantum mechanical effects,
                which are inherently random according to our current understanding of physics.
              </p>
              <p className="text-sm text-muted-foreground">
                Unlike algorithm-based pseudo-random number generators, quantum randomness is unpredictable
                at a fundamental level, making it ideal for cryptography, scientific simulations, and statistical sampling.
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="how-it-works">
            <AccordionTrigger>How Does It Work?</AccordionTrigger>
            <AccordionContent>
              <p className="text-sm text-muted-foreground mb-2">
                This app uses the ANU Quantum Random Numbers API, which measures quantum fluctuations in a vacuum. 
                At quantum scales, empty space isn't truly empty, but filled with virtual particles appearing and disappearing.
              </p>
              <p className="text-sm text-muted-foreground">
                By measuring these quantum fluctuations with specialized equipment, scientists can generate numbers 
                that are fundamentally random and cannot be predicted, even with perfect knowledge of the universe.
              </p>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="applications">
            <AccordionTrigger>Applications of Quantum Randomness</AccordionTrigger>
            <AccordionContent>
              <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
                <li>Cryptography and cybersecurity</li>
                <li>Scientific simulations and modeling</li>
                <li>Statistical sampling and surveys</li>
                <li>Lottery and gaming systems</li>
                <li>Monte Carlo methods in finance</li>
                <li>Fairness in competitive environments</li>
              </ul>
            </AccordionContent>
          </AccordionItem>

          <AccordionItem value="vs-pseudo">
            <AccordionTrigger>Quantum vs. Pseudo-Random</AccordionTrigger>
            <AccordionContent>
              <p className="text-sm text-muted-foreground">
                Pseudo-random numbers are generated by mathematical algorithms. They appear random but are actually 
                deterministic and will eventually repeat. Quantum random numbers are based on measurements of quantum 
                mechanical phenomena that are truly random and unpredictable, according to our current understanding of physics. 
                This makes them superior for applications requiring true randomness.
              </p>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </CardContent>
    </Card>
  );
};

export default AboutQuantum;
